# Central Limit Theorem — Solar & Wind Dataset
**Dataset:** Hourly Electricity Consumption and Production (Kaggle)

<b>Desiree Valois</b>
<br>Computer Engineer

In [1]:
# imports and packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# load dataset
# downloaded from: https://www.kaggle.com/datasets/stefancomanita/hourly-electricity-consumption-and-production
df = pd.read_csv(r"dataset/electricity-sample-dataset.csv")
df[["Solar","Wind"]].head()

   Solar  Wind
0      0    79
1      0    96
2      0   142
3      0   191
4      0   159

In [3]:
# summary of dataframe
df[["Solar","Wind"]].info()

<class 'pandas.DataFrame'>
RangeIndex: 54170 entries, 0 to 54169
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Solar   54170 non-null  int64
 1   Wind    54170 non-null  int64
dtypes: int64(2)
memory usage: 846.5 KB

In [4]:
# summary of statistics (raw data - non-normal)
df[["Solar","Wind"]].describe()

              Solar          Wind
count  54170.000000  54170.000000
mean     171.808381    771.727691
std      257.257698    666.534396
min        0.000000    -26.000000
25%        0.000000    228.000000
50%        3.000000    571.000000
75%      302.000000   1167.000000
max     1552.000000   2811.000000

## Apply Central Limit Theorem
Large sample sizes are mostly non-normal. Used CLT to convert the data to normal:
draw 50 random samples of size 30 and use the **sample means** as the working dataset.

In [5]:
# storage of means
means_data = {"Solar": [], "Wind": []}

np.random.seed(42)

# sampling means
for _ in range(50):  # 50 times
    for c in ["Solar", "Wind"]:
        sample = np.random.choice(df[c], size=30, replace=True)
        means_data[c].append(np.mean(sample))

In [6]:
df_means = pd.DataFrame(means_data)
df_means

         Solar         Wind
0   145.133333   705.033333
1   251.333333   694.466667
2   151.533333   976.033333
3   236.166667   801.300000
4   161.466667   874.933333
5   130.966667   620.266667
6   213.933333   967.900000
7   152.866667   746.500000
8   151.000000   860.766667
9   203.600000  1011.000000
10  128.766667   774.466667
11  114.066667   754.933333
12  106.266667   982.700000
13  155.300000   704.066667
14   97.200000   797.133333
15  194.866667   693.000000
16  184.266667   753.866667
17  184.800000   694.833333
18  123.266667   810.200000
19  216.600000  1001.100000
20  138.900000   898.900000
21  191.200000   787.866667
22  184.400000   551.633333
23  134.266667   825.766667
24  247.666667   664.666667
25  154.233333   688.500000
26  138.466667   818.933333
27  234.800000   666.433333
28  134.300000   534.433333
29  202.233333   607.300000
30  164.900000   681.100000
31  173.600000   703.466667
32  166.400000   614.566667
33  209.933333   648.400000
34  246.466667   878.366667
35  136.033333   861.133333
36  150.266667   763.500000
37  168.400000   688.066667
38  146.200000   491.900000
39  165.033333   753.133333
40  211.500000   811.733333
41  152.866667   813.133333
42  141.800000   742.066667
43  145.266667   761.433333
44  295.666667   685.800000
45  220.500000   837.433333
46  210.066667   938.900000
47  222.900000   861.933333
48  131.133333   653.800000
49  101.533333   671.900000

In [7]:
df_means.to_csv(r"dataset/electricity-clt-dataset.csv", index=False)
print("CLT dataset saved!")

CLT dataset saved!